Repository austation/austation, pull requests merged in 2019-12, with the labels that each got.

#641 [MIRROR] Removes unused & undefined spans
  _maps/RandomZLevels/SnowCabin.dmm
  code/datums/components/fantasy/_fantasy.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/law.dm
  code/game/machinery/limbgrower.dm
  code/game/machinery/teleporter.dm
  code/game/objects/items/AI_modules.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/structures/fireaxe.dm
  code/modules/assembly/flash.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
  code/modules/power/singularity/particle_accelerator/particle_control.dm
  code/modules/spells/spell_types/charge.dm
  code/modules/spells/spell_types/lichdom.dm
  code/modules/spells/spell_types/summonitem.dm
  code/modules/surgery/dental_implant.dm
  interface/stylesheet.dm
Labels: Map Edit, Removal

#642 [MIRROR] radstorm alarm no longer grapes your ears
  sound/misc/bloblarm.ogg
Labels: Sound

#645 [MIRROR] Add map icon states for the ED-209
  icons/mob/aibots.dmi
Labels: Sprites

#749 Adds hair colour changing to mirrors
  austation/code/game/objects/structures/mirror.dm
  austation/includes.dm
Labels: Feature

#750 Ports catbans from hippie
  austation/code/_DEFINES/admin.dm
  austation/code/controllers/subsystem/job.dm
  austation/code/modules/admin/topic.dm
  austation/code/modules/jobs/job_types/job.dm
  austation/code/modules/mob/dead/new_player/new_player.dm
  austation/define_includes.dm
  austation/includes.dm
  code/controllers/subsystem/job.dm
  code/datums/dna.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/preferences.dm
  tgstation.dme
Labels: Feature

#757 Adds Thanos Car
  austation/code/modules/vehicles/cars/thanoscar.dm
  austation/icons/obj/vehicles.dmi
  austation/includes.dm
Labels: Feature

#789 [MIRROR] Corrects my misconceptions about the supermatter
  code/modules/power/supermatter/supermatter.dm
Labels: Code Improvement, Upstream PR Merged

#804 [MIRROR] E.X.P.E.R.I-Mentor Overhaul Part the First: Research Notes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/controllers/subsystem/research.dm
  code/modules/research/experimentor.dm
Labels: Balance/Rebalance, Feature, Map Edit, Tweak, Upstream PR Merged

#915 adds MAP EXPORTS BOIII
  austation/code/modules/admin/verbs/mapping.dm
  austation/code/modules/mapping/writer.dm
  austation/includes.dm
  code/modules/admin/verbs/mapping.dm
Labels: Feature
