Repository austation/austation, pull requests merged in 2019-11, with the labels that each got.

#374 tgui-next update
  tgui-next/bin/tgui
  tgui-next/packages/tgui/interfaces/ChemAcclimator.js
  tgui-next/packages/tgui/interfaces/ChemDebugSynthesizer.js
  tgui-next/packages/tgui/interfaces/ChemFilter.js
  tgui-next/packages/tgui/interfaces/ChemPress.js
  tgui-next/packages/tgui/interfaces/ChemSplitter.js
  tgui-next/packages/tgui/interfaces/ChemSynthesizer.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: UI

#392 Fixes holodeck
  code/modules/holodeck/computer.dm
Labels: Fix, Upstream PR Merged

#393 A few examine fixes
  code/game/objects/items/credit_holochip.dm
  code/game/objects/items/devices/electroadaptive_pseudocircuit.dm
Labels: Fix, Upstream PR Merged

#394 Dice bags spawn the special die in the bag
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/dice.dm
Labels: Fix, Upstream PR Merged

#422 I am retarded and didn't squash merge
  austation/changes.txt
  code/modules/lighting/lighting_source.dm
Labels: Tweak

#457 yeet elances
  austation/changes.txt
  austation/code/game/objects/items/twohanded.dm
  austation/includes.dm
Labels: Balance/Rebalance, Feature

#549 [MIRROR] Migrates equipment slowdown to a movespeed mod
  code/__DEFINES/movespeed_modification.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/mob.dm
Labels: Balance/Rebalance, Fix

#596 [PHIL YOU MAKE ME ANGRY, PHIL] [MIRROR] Makes a generic recursive movement tracker
  code/datums/components/orbiter.dm
  code/datums/movement_detector.dm
  tgstation.dme
Labels: Upstream PR Merged

#612 [MIRROR] lets you tape knives to cleanbots you know you want to
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  icons/mob/aibots.dmi
Labels: Sprites

#608 Working minimum player config
  code/game/gamemodes/game_mode.dm
Labels: Config Update

#617 MK.I SWAT Armor Resprite
  austation/code/modules/clothing/spacesuit/miscellaneous.dm
  austation/icons/mob/clothing/suit.dmi
  austation/icons/obj/clothing/suit.dmi
  austation/includes.dm
Labels: Sprites
