Repository austation/austation, pull requests merged in 2020-08, with the labels that each got.

#2030 Exporting Burgers, Breads and misc
  austation/code/modules/cargo/exports/food_and_drink/bread.dm
  austation/code/modules/cargo/exports/food_and_drink/burger.dm
  austation/code/modules/cargo/exports/food_and_drink/food_mixtures.dm
  austation/includes.dm
Labels: Feature

#2046 MKA and Ion Thrusters
  austation/code/game/mecha/equipment/tools/other_tools.dm
  austation/code/game/mecha/equipment/tools/work_tools.dm
  austation/code/game/mecha/equipment/weapons/weapons.dm
  austation/code/modules/research/designs/mecha_designs.dm
  austation/code/modules/research/techweb/all_nodes.dm
  austation/includes.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Feature, Sprites

#2049 Adds Inhand Sprites For Cigarette Packets
  austation/code/game/objects/items/storage/fancy.dm
  austation/icons/mob/inhands/items_lefthand.dmi
  austation/icons/mob/inhands/items_righthand.dmi
  austation/includes.dm
Labels: Feature

#2028 goon bread except we do it differently it so that it's under AGPL
  _maps/RandomRooms/10x10/sk_rdm210_pool.dmm
  _maps/RandomRooms/3x3/sk_rdm208_roo2.dmm
  _maps/RandomRooms/3x3/sk_rdm211_loafer.dmm
  _maps/RandomRooms/3x5/sk_rdm207_roo1.dmm
  _maps/RandomRooms/5x4/sk_rdm209_roo3.dmm
  _maps/map_files/Austation/Austation.dmm
  austation/code/_DEFINES/movespeed_modification.dm
  austation/code/modules/cargo/exports/food_and_drink/processed.dm
  austation/code/modules/food_and_drinks/food/snacks_bread.dm
  austation/code/modules/mapping/random_rooms.dm
  austation/code/modules/pool/pool_controller.dm
  austation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  austation/code/modules/recycling/disposal/construction.dm
  austation/code/modules/recycling/disposal/loafer.dm
  austation/define_includes.dm
  austation/icons/obj/atmospherics/machines/loafer.dmi
  austation/icons/obj/food/burgerbread.dmi
  austation/includes.dm
Labels: Feature, Map Edit, Testmerge Candidate

#2059 chef syndi whetstone
  austation/code/game/objects/items/sharpener.dm
  austation/code/modules/uplink/uplink_items.dm
  austation/icons/obj/kitchen.dmi
  austation/includes.dm
Labels: Feature, Terra Approved

#2061 Adds a radial menu to drone style selection
  austation/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  austation/code/modules/mob/living/simple_animal/friendly/drone/visuals_icons.dm
  austation/includes.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
Labels: Feature

#2062 Nanite changes
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
Labels: Balance/Rebalance, Feature

#2076 Service skirtborg lights fix
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
  austation/icons/mob/robot.dmi
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix

#2060 Make Botany Great Again
  austation/code/modules/hydroponics/grown.dm
  austation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  austation/includes.dm
Labels: Tweak

#2077 adds miasma to lavaland atmos
  code/datums/atmosphere/planetary.dm
Labels: Tweak

#2083 Couple of minor mapping updates for Austation
  _maps/map_files/Austation/Austation.dmm
Labels: Feature, Map Edit, Tweak

#2104 Sepchems Fix
  austation/code/modules/hydroponics/grown.dm
Labels: Fix

#2075 Adds a jumping ability to player-controlled roos, also more roos
  austation/code/datums/mutations/jumpy.dm
  austation/code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
  austation/icons/mob/actions/actions.dmi
  austation/icons/mob/kangaroos.dmi
  austation/includes.dm
Labels: Feature

#2093 Borg icon selection using RADIALS!
  austation/code/modules/mob/living/silicon/robot/robot.dm
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
  austation/includes.dm
  code/_onclick/hud/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature, Refactor

#2110 more roo runtimes smh
  austation/code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
Labels: Fix

#2081 ports bluespace jars
  austation/code/game/objects/items/bluespace_jar.dm
  austation/code/modules/research/designs/bluespace_designs.dm
  austation/code/modules/research/techweb/all_nodes.dm
  austation/icons/obj/bluespace_jar.dmi
  austation/includes.dm
Labels: Feature

#2080 Cursed oxygen tank tendril loot
  austation/code/game/objects/items/tanks/tank_types.dm
  austation/includes.dm
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Feature

#2084 new aussie drinks!
  austation/code/modules/food_and_drinks/recipes/drinks_recipes.dm
  austation/code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  austation/code/modules/reagents/chemistry/reagents.dm
  austation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  austation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
  austation/icons/obj/drinks.dmi
  austation/includes.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
Labels: Feature

#2085 You can now craft makeshift pistols
  austation/code/datums/components/crafting/recipes.dm
  austation/code/modules/projectiles/boxes_magazine/internal/makeshift_mags.dm
  austation/code/modules/projectiles/guns/ballistic/makeshift_pistol.dm
  austation/icons/obj/guns.dmi
  austation/includes.dm
Labels: Feature, Sprites

#2088 Xenobiology Steroid crate
  austation/code/modules/cargo/packs.dm
  austation/includes.dm
Labels: Feature

#2128 oops
  austation/includes.dm
Labels: Fix

#2129 Makes the pool smaller
  _maps/RandomRooms/10x10/sk_rdm210_pool.dmm
  austation/code/modules/mapping/random_rooms.dm
Labels: Fix, Map Edit

#2092 Adds Australium items
  austation/code/_DEFINES/misc.dm
  austation/code/_DEFINES/traits.dm
  austation/code/_GLOBALS/misc.dm
  austation/code/modules/mob/living/carbon/human/examine.dm
  austation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/client/preferences.dm
Labels: Feature, Terra Approved

#2099 Potato Battery Salt Nerf Removal
  austation/code/modules/hydroponics/plant_genes.dm
  austation/includes.dm
Labels: Tweak

#2100 The Poleaxe
  austation/code/datums/components/crafting/crafting.dm
  austation/code/game/objects/items/twohanded.dm
  austation/icons/mob/inhands/weapons/polearms_lefthand.dmi
  austation/icons/mob/inhands/weapons/polearms_righthand.dmi
  austation/icons/obj/items_and_weapons.dmi
  austation/includes.dm
Labels: Feature

#2105 Slime Reproduction Potions Buff
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
Labels: Tweak

#2112 mutant bread now inherits bread force (and reagent fix)
  austation/code/modules/food_and_drinks/food/snacks_bread.dm
  austation/code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak

#2113 Adds the Handy sprite to engiborg radial
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix

#2115 Swat Armour Sprite Update
  austation/icons/mob/clothing/suit.dmi
  austation/icons/obj/clothing/suit.dmi
Labels: Tweak

#2120 Decreases floor tile melting point
  code/game/turfs/open/floor.dm
Labels: Tweak

#2107 Ports femur breaker
  austation/code/datums/components/crafting/recipes.dm
  austation/code/game/objects/structures/femur_breaker.dm
  austation/icons/obj/machines/femur_breaker.dmi
  austation/includes.dm
  austation/sound/effects/femur_breaker.ogg
Labels: Feature, Sound, Sprites

#2111 Botany Tweaks
  austation/code/modules/clothing/head/helmet.dm
  austation/code/modules/clothing/masks/miscellaneous.dm
  austation/code/modules/clothing/under/miscellaneous.dm
  austation/code/modules/hydroponics/grown/towercap.dm
  austation/icons/mob/head.dmi
  austation/icons/mob/uniform.dmi
  austation/icons/obj/clothing/hats.dmi
  austation/includes.dm
Labels: Feature, Tweak

#2125 Organ and Burger export rebalancing
  austation/code/modules/cargo/exports/food_and_drink/burger.dm
  austation/code/modules/cargo/exports/organs.dm
Labels: Balance/Rebalance, Tweak

#2130 Radical Radials - pai holochassis
  austation/code/modules/mob/living/silicon/pai/pai_shell.dm
  austation/includes.dm
  code/_onclick/hud/pai.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
Labels: Tweak

#2135 Adds the forgotten maint pool's filter and fixes the pool border not rotating correctly
  _maps/RandomRooms/10x10/sk_rdm210_pool.dmm
  austation/code/game/objects/effects/decals/turfdecal/markings.dm
  austation/icons/turf/decals.dmi
Labels: Feature, Map Edit

#2117 [PORT] Ports Orbital Station
  _maps/map_files/OrbitalStation/OrbitalStation.dmm
  _maps/orbitalstation.json
  config/maps.txt
Labels: Config Update, Map Edit, Port

#2126 TK Hugs
  austation/code/datums/mutations/telekinesis.dm
  austation/includes.dm
Labels: Tweak

#2136 Fire immune suits buff
  code/__DEFINES/atmospherics.dm
Labels: Tweak

#2141 Whoops
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix

#2145 Banter roundend sound
  sound/roundend/banter.ogg
Labels: Sound

#2149 Makeshift pistol 'balance pass'
  austation/code/modules/projectiles/guns/ballistic/makeshift_pistol.dm
Labels: Tweak

#2156 You can build plating on dug asteroid surfaces
  code/game/turfs/open/floor/plating.dm
Labels: Tweak

#2160 Slime Potion Fix
  austation/code/modules/mob/living/simple_animal/slime/slime.dm
  austation/code/modules/research/xenobiology/crossbreeding/_potions.dm
  austation/includes.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
Labels: Fix

#2157 Ports the floor painter from para
  austation/code/game/objects/items/devices/floor_painter.dm
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
  austation/code/modules/research/designs/autolathe_designs.dm
  austation/icons/obj/device.dmi
  austation/icons/turf/floors.dmi
  austation/includes.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature

#2170 More australium-able items
  austation/code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature

#2181 Floor Painter fix
  austation/code/game/objects/items/devices/floor_painter.dm
Labels: Fix, High Priority
