Repository austation/austation, pull requests merged in 2020-06, with the labels that each got.

#1817 goon shuttle sounds
  code/modules/shuttle/emergency.dm
  goon/README.md
  goon/sound/misc/shuttle_arrive1.ogg
  goon/sound/misc/shuttle_centcom.ogg
  goon/sound/misc/shuttle_enroute.ogg
  goon/sound/misc/shuttle_recalled.ogg
Labels: Feature, Sound, Terra Approved

#1794 Bluespace belts
  austation/code/game/objects/items/storage/belt.dm
  austation/code/modules/research/designs/bluespace_designs.dm
  austation/icons/obj/clothing/belts.dmi
  austation/includes.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#1803 Adds gas miners to more maps
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit

#1804 [Port] Buffs circle game
  austation/code/game/objects/items/weaponry.dm
  austation/code/modules/mob/living/carbon/human/emote.dm
  austation/includes.dm
  code/datums/mutations/hulk.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/emote.dm
Labels: Feature, Port

#1827 fixes bluesapce belts
  austation/code/game/objects/items/storage/belt.dm
Labels: Fix

#1823 Removes Cheesing From Lavaland Stuff
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  austation/code/game/turfs/open/lava.dm
  austation/includes.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
Labels: Balance/Rebalance, Map Edit, Tweak

#1822 D e a t h s k y
  austation/code/game/machinery/syndicatebeacon.dm
  austation/code/modules/mob/living/simple_animal/bot/deathsky.dm
  austation/code/modules/uplink/uplink_items.dm
  austation/icons/mob/aibots.dmi
  austation/includes.dm
  code/game/machinery/computer/arcade.dm
Labels: Feature

#1825 nerfs 3 fucking pixels sound bit
  sound/roundend/3fuckingpixels.ogg
Labels: Balance/Rebalance, Sound, Terra Approved

#1811 Adds craftable epipens
  austation/code/modules/reagents/reagent_containers/custompen.dm
  austation/code/modules/research/designs/medical_designs.dm
  austation/includes.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/syringe.dmi
Labels: Feature, Sprites

#1830 Floor heat capacity tweak
  code/game/turfs/open/floor.dm
Labels: Tweak

#1831 nerfs confusion
  code/modules/mob/living/living.dm
Labels: Balance/Rebalance

#1832 Crewsimov
  austation/code/datums/ai_laws.dm
  austation/code/game/objects/items/AI_modules.dm
  austation/code/modules/research/designs/AI_module_designs.dm
  config/game_options.txt
Labels: Config Update

#1841 golems can now actually speak their languages
  austation/code/modules/mob/living/carbon/human/species_type/golems.dm
Labels: Fix

#1860 Gottem Emoji
  icons/emoji.dmi
Labels: Feature, RED LABEL, Sprites, Terra Approved

#1844 Adds Kangaroos
  austation/code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
  austation/icons/mob/kangaroos.dmi
  austation/includes.dm
Labels: Feature, Sprites, Terra Approved

#1845 Laser pointer re-balance
  code/game/objects/items/devices/laserpointer.dm
Labels: Balance/Rebalance

#1886 HUD Sunnies Sprite Update
  austation/code/modules/clothing/glasses/hud.dm
  austation/icons/mob/eyes.dmi
  austation/icons/obj/clothing/glasses.dmi
  austation/includes.dm
Labels: Sprites
