Repository austation/austation, pull requests merged in 2020-04, with the labels that each got.

#1474 Ports medkit changes from tg
  austation/code/game/objects/items/storage/firstaid.dm
  austation/code/modules/jobs/job_types/chief_medical_officer.dm
  austation/code/modules/jobs/job_types/medical_doctor.dm
  austation/icons/obj/storage.dmi
  austation/includes.dm
Labels: Feature

#1482 Ports some borg sprites from citadel
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
  austation/icons/mob/robot.dmi
  austation/includes.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature, Port, Sprites

#1520 I would be fine with the hive...
  austation/sound/roundend/3fuckingpixels.ogg
Labels: Sound

#1521 Fixes an issue where module upgrades would be consumed with no change when borg had no mind
  code/game/objects/items/robot/robot_upgrades.dm
Labels: Fix

#1525 Defines hat_offset for new sprites
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix

#1564 The Dawson Memorial Emote
  austation/code/modules/mob/living/emote.dm
  austation/includes.dm
Labels: Feature

#1559 Bruh moment [Meme PR]
  austation/code/modules/mob/living/human/emote.dm
  austation/includes.dm
  austation/sound/misc/bruh.ogg
Labels: Feature, Sound

#1582 Makes sandbox menu better
  code/game/gamemodes/sandbox/h_sandbox.dm
Labels: Feature

#1592 Gygaxes require silver and gold instead of diamonds (like before the rebase)
  austation/code/modules/research/designs/mechfabricator_designs.dm
Labels: Tweak

#1602 Removes AI and borg upload from techweb
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Removal

#1604 Added Bruh Moment event [MEME PR]
  austation/code/modules/events/bruh_moment.dm
  austation/includes.dm
Labels: Feature

#1618 Removes skewium from possible bounties
  code/modules/cargo/bounties/reagent.dm
Labels: Removal, Terra Approved
