Repository austation/austation, pull requests merged in 2020-05, with the labels that each got.

#1627 [MIRROR] Adds request consoles to every department
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Map Edit, Upstream PR Merged

#1705 The Emote Addition PR
  austation/code/datums/emotes.dm
  austation/code/modules/mob/living/carbon/emote.dm
  austation/code/modules/mob/living/carbon/human/emote.dm
  austation/code/modules/mob/living/carbon/human/species_type/felinid.dm
  austation/code/modules/mob/living/emote.dm
  austation/code/modules/mob/living/human/emote.dm
  austation/code/modules/mob/living/silicon/robot/emote.dm
  austation/code/modules/mob/mob_defines.dm
  austation/includes.dm
  austation/sound/misc/goughdemn.ogg
  austation/sound/misc/nono.ogg
  austation/sound/misc/yesYES.ogg
  code/modules/mob/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/mob_defines.dm
Labels: Feature

#1717 Dead mobs no longer spawn split-personality and imaginary friends
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/split_personality.dm
Labels: Fix

#1718 Emote Fix
  austation/code/modules/mob/living/carbon/human/emote.dm
Labels: Fix

#1712 [PORT] Racial languages from TG
  austation/code/_DEFINES/language.dm
  austation/code/modules/language/buzzwords.dm
  austation/code/modules/language/calcic.dm
  austation/code/modules/language/language_holder.dm
  austation/code/modules/language/moffic.dm
  austation/code/modules/language/shadowtongue.dm
  austation/code/modules/language/sylvan.dm
  austation/code/modules/language/terrum.dm
  austation/code/modules/language/voltaic.dm
  austation/code/modules/mob/living/carbon/human/species.dm
  austation/code/modules/mob/living/carbon/human/species_type/apid.dm
  austation/code/modules/mob/living/carbon/human/species_type/ethereal.dm
  austation/code/modules/mob/living/carbon/human/species_type/flypeople.dm
  austation/code/modules/mob/living/carbon/human/species_type/golems.dm
  austation/code/modules/mob/living/carbon/human/species_type/mothmen.dm
  austation/code/modules/mob/living/carbon/human/species_type/plasmamen.dm
  austation/code/modules/mob/living/carbon/human/species_type/podpeople.dm
  austation/code/modules/mob/living/carbon/human/species_type/shadowpeople.dm
  austation/code/modules/mob/living/carbon/human/species_type/skeletons.dm
  austation/code/modules/surgery/organs/tongue.dm
  austation/define_includes.dm
  austation/icons/misc/austation_language.dmi
  austation/icons/obj/austation_surgery.dmi
  austation/includes.dm
  code/modules/language/language_holder.dm
  code/modules/surgery/organs/tongue.dm
Labels: Feature, Port, Sprites, Testmerge Candidate

#1749 [MIRROR] BeeCoin shop & Loadout additions
  beestation.dme
  code/modules/client/loadout/loadout.dm
  code/modules/client/loadout/loadout_accessories.dm
  code/modules/client/loadout/loadout_cosmestics.dm
  code/modules/client/loadout/loadout_footwear.dm
  code/modules/client/loadout/loadout_general.dm
  code/modules/client/loadout/loadout_hat.dm
  code/modules/client/loadout/loadout_ooc.dm
  code/modules/client/loadout/loadout_suit.dm
  code/modules/client/loadout/loadout_uniform.dm
  code/modules/client/preferences.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/security.dm
Labels: Code Improvement, Feature, Fix, Grammar and Formatting, Upstream PR Merged

#1735 Adds sarin
  austation/code/game/objects/items/storage/uplink_kits.dm
  austation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  austation/code/modules/reagents/chemistry/recipes/toxins.dm
  austation/code/modules/reagents/reagent_containers/bottle.dm
  austation/includes.dm
  code/game/objects/items/storage/uplink_kits.dm
Labels: Feature, Removal
