Repository austation/austation, pull requests merged in 2020-12, with the labels that each got.

#2682 Bluespace jars can now contain reagents 2: Electric boogaloo
  austation/code/game/objects/items/bluespace_jar.dm
Labels: Tweak

#2697 Sandbox Menu Fix
  code/game/gamemodes/sandbox/h_sandbox.dm
Labels: Fix, Terra Approved

#2705 Removes Admin Only Sandbox Panel
  code/game/gamemodes/sandbox/h_sandbox.dm
Labels: Fix, Removal

#2712 [s] Revert "tail entwining, again"
  code/modules/mob/living/living.dm
Labels: Removal, Revert

#2714 Removes orphaned pipes
  _maps/map_files/Austation/Austation.dmm
Labels: Map Edit, Removal

#2618 The Deep Bag of Holding
  _maps/templates/deepbluespace.dmm
  austation/code/game/objects/items/deepbagofholding.dm
  austation/icons/obj/deepbagofholding.dmi
  austation/includes.dm
Labels: Feature, Map Edit, Sprites

#2738 Add Anzac Day
  code/modules/holiday/holidays.dm
Labels: Feature

#2744 Roundend messages are now sanitized
  austation/code/_HELPERS/roundend.dm
Labels: Fix, High Priority, Terra Approved

#2748 Revert "Add Anzac Day" (merged upstream)
  code/modules/holiday/holidays.dm
Labels: Revert

#2762 OOC is now logged in a discord channel
  austation/code/_HELPERS/roundend.dm
  austation/code/modules/client/verbs/ooc.dm
  austation/includes.dm
Labels: Feature

#2767 fixes ooc messages
  austation/code/_HELPERS/roundend.dm
  austation/code/modules/client/verbs/ooc.dm
Labels: High Priority

#2774 Revert "[MIRROR] Adds the old gas mask back."
  code/_globalvars/lists/maintenance_loot.dm
  code/controllers/subsystem/traumas.dm
  code/game/machinery/gulag_teleporter.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/shuttle/emergency.dm
Labels: Revert, Upstream PR Merged
