Repository austation/austation, pull requests merged in 2020-07, with the labels that each got.

#1895 Updates the firelock frame's collision to be like directional windows
  code/game/machinery/doors/firedoor.dm
Labels: Tweak

#1861 Adds new borg sprites
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
  austation/icons/mob/robot.dmi
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Sprites

#1917 Makes it so Freezers/Heaters can change layers through the maintenance panel
  austation/code/modules/atmospherics/machinery/atmosmachinery.dm
  austation/code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  austation/includes.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Labels: Tweak

#1936 actually adds crewsimov board to techweb
  code/modules/research/techweb/all_nodes.dm
Labels: Fix, High Priority

#1949 Sunglasses in Hand Sprite Fix
  austation/code/modules/clothing/glasses/hud.dm
  austation/icons/mob/inhands/clothing_lefthand.dmi
  austation/icons/mob/inhands/clothing_righthand.dmi
Labels: Fix

#1910 Adds Pools to Metastation
  _maps/_basemap.dm
  _maps/austation.json
  _maps/map_files/Austation/Austation.dmm
  austation/code/_DEFINES/pool.dm
  austation/code/_DEFINES/traits.dm
  austation/code/_GLOBALS/misc.dm
  austation/code/_GLOBALS/pool_globals.dm
  austation/code/datums/elements/swimming.dm
  austation/code/modules/pool/pool_controller.dm
  austation/code/modules/pool/pool_drain.dm
  austation/code/modules/pool/pool_effects.dm
  austation/code/modules/pool/pool_main.dm
  austation/code/modules/pool/pool_noodles.dm
  austation/code/modules/pool/pool_structures.dm
  austation/code/modules/pool/pool_wires.dm
  austation/define_includes.dm
  austation/icons/effects/96x96.dmi
  austation/icons/mob/inhands/items_lefthand.dmi
  austation/icons/mob/inhands/items_righthand.dmi
  austation/icons/obj/machines/pool.dmi
  austation/icons/obj/toy.dmi
  austation/icons/turf/pool.dmi
  austation/includes.dm
  austation/sound/effects/fillingwatter.ogg
  austation/sound/effects/pooldrain.ogg
  austation/sound/effects/slosh.ogg
  austation/sound/effects/slosh1.ogg
  austation/sound/effects/slosh2.ogg
  austation/sound/effects/splash.ogg
  austation/sound/effects/watersplash.ogg
  austation/sound/misc/crack.ogg
  austation/sound/misc/crunch.ogg
  config/maps.txt
Labels: Code Improvement, Config Update, Feature, Map Edit, Sound, Sprites

#1923 Ports brain cortex surgery from /tg/
  austation/code/_DEFINES/mobs.dm
  austation/code/_DEFINES/traits.dm
  austation/code/modules/research/designs/medical_designs.dm
  austation/code/modules/surgery/advanced/bioware/cortex_folding.dm
  austation/code/modules/surgery/advanced/bioware/cortex_imprint.dm
  austation/define_includes.dm
  austation/includes.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/lobotomy.dm
Labels: Feature

#1950 Maint kangaroos
  _maps/RandomRooms/3x3/sk_rdm108_roo2.dmm
  _maps/RandomRooms/3x5/sk_rdm107_roo1.dmm
  _maps/RandomRooms/5x4/sk_rdm109_roo3.dmm
  austation/code/modules/mapping/random_rooms.dm
  austation/includes.dm
Labels: Feature, Map Edit, Terra Approved

#1969 Roos rebalance
  austation/code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
Labels: Critical Priority, Tweak

#1902 Adds holofan to engineering borgs
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature

#1957 Rename cup to doctors mug
  austation/code/modules/food_and_drinks/drinks/drinks.dm
Labels: Tweak

#1958 Sell Organs for Credits
  austation/code/modules/cargo/exports/organs.dm
  austation/includes.dm
Labels: Feature

#1979 Removes farting from Self respiration symptom
  code/datums/diseases/advance/symptoms/oxygen.dm
Labels: Removal, Terra Approved

#1953 Nitryl Stim Buff Reconfigure
  austation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/surgery/organs/lungs.dm
Labels: Balance/Rebalance

#1968 AuStation piping update + minor fixes
  _maps/map_files/Austation/Austation.dmm
Labels: Feature, Fix, Map Edit, Removal, Terra Approved

#1978 Drone quality of life improvement
  austation/code/modules/mob/living/simple_animal/friendly/drone/drone.dm
  austation/code/modules/mob/living/simple_animal/friendly/drone/drone_movement.dm
  austation/code/modules/mob/living/simple_animal/friendly/drone/emote.dm
  austation/includes.dm
Labels: Feature

#1989 No more piss pools
  austation/icons/turf/pool.dmi
Labels: Sprites

#1993 Add a pool to randomized maints
  _maps/RandomRooms/10x10/sk_rdm110_pool.dmm
  austation/code/modules/mapping/random_rooms.dm
Labels: Feature, Map Edit

#1998 Adds kelvin to medical scanner
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/objects/items/devices/scanners.dm
Labels: Feature

#1983 You can now make furniture out of human leather
  austation/code/game/objects/structures/humanfurniture.dm
  austation/icons/obj/chairs.dmi
  austation/icons/obj/tables.dmi
  austation/includes.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/structures/tables_racks.dm
Labels: Feature

#2023 uh oh, i forgot to add a line which made human tables unbuildable
  code/game/objects/items/stacks/sheets/leather.dm
Labels: Fix

#2002 Added in the missing sounds of the pool
  austation/code/game/sound.dm
  austation/includes.dm
  austation/sound/effects/water_wade1.ogg
  austation/sound/effects/water_wade2.ogg
  austation/sound/effects/water_wade3.ogg
  austation/sound/effects/water_wade4.ogg
Labels: Fix, Sound

#1976 Headpats now gives a mood buff
  austation/code/datums/mood_event/generic_positive_events.dm
  austation/includes.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Balance/Rebalance

#2039 Revert "Adds gas miners to more maps" to fix mirror coomflicts
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Revert

#2032 Pool decals causing travis to kill himself
  _maps/RandomRooms/10x10/sk_rdm110_pool.dmm
  austation/code/modules/pool/pool_main.dm
Labels: Fix, Map Edit

#2045 Rebalancing Virology
  _maps/map_files/Austation/Austation.dmm
Labels: Critical Priority, Fix, Map Edit, Removal, Terra Approved

#2007 Drained pools now paralyse borgs
  austation/code/modules/pool/pool_main.dm
Labels: Tweak

#2024 Adds a plumbing area to austation
  _maps/map_files/Austation/Austation.dmm
  austation/code/game/area/Space_Station_13_areas.dm
  austation/includes.dm
Labels: Feature, Map Edit

#2044 Minor Arrivals Mapping Error
  _maps/map_files/Austation/Austation.dmm
Labels: Fix, Map Edit
