Repository austation/austation, pull requests merged in 2020-09, with the labels that each got.

#2148 Mining Tweaks and Occult Tank
  austation/code/game/objects/items/tanks/jetpack.dm
  austation/code/game/objects/items/tanks/tank_types.dm
  austation/code/game/objects/items/tanks/tanks.dm
  austation/code/modules/mining/lavaland/necropolis_chests.dm
  austation/code/modules/research/techweb/all_nodes.dm
  austation/icons/obj/tank.dmi
  austation/includes.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Removal, Tweak

#2171 Observers don't need to be told about the correct way to load the makeshift pistol
  austation/code/modules/projectiles/guns/ballistic/makeshift_pistol.dm
Labels: Fix

#2182 APC On/Off Wire Tweak
  austation/code/datums/wires/apc.dm
  austation/includes.dm
Labels: Tweak

#2183 Ports RDX and TaTP from /tg/
  austation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  austation/code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  austation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  austation/code/modules/reagents/chemistry/recipes.dm
  austation/code/modules/reagents/chemistry/recipes/others.dm
  austation/code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  austation/code/modules/reagents/chemistry/recipes/toxins.dm
  austation/includes.dm
  code/game/objects/structures/lavaland/geyser.dm
Labels: Feature

#2206 Rings are now toggle-able
  austation/code/modules/mob/living/carbon/human/examine.dm
  austation/code/modules/mob/mob.dm
  austation/code/modules/mob/mob_defines.dm
  austation/includes.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature

#2204 Fixes borg lights again(tm)
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Fix

#2144 [Port] Rats Rats we are the rats!
  _maps/RandomRooms/3x3/sk_rdm212_cheese.dmm
  austation/code/_globalvars/lists/maintenance_loot.dm
  austation/code/controllers/configuration/entries/game_options.dm
  austation/code/modules/food_and_drinks/food/snacks_other.dm
  austation/code/modules/food_and_drinks/recipes/recipes_misc.dm
  austation/code/modules/mapping/random_rooms.dm
  austation/code/modules/mob/living/simple_animal/friendly/mouse.dm
  austation/code/modules/mob/living/simple_animal/hostile/regalrat.dm
  austation/icons/mob/actions/actions.dmi
  austation/icons/mob/regalrat.dmi
  austation/icons/obj/food/cheese.dmi
  austation/includes.dm
  code/controllers/subsystem/mobs.dm
Labels: Code Improvement, Feature, Map Edit, Port, Sprites

#2205 Adds more dresses and clothings
  austation/code/modules/cargo/packs/costumes_toys.dm
  austation/code/modules/cargo/packs/packs.dm
  austation/code/modules/client/loadout/loadout_uniform.dm
  austation/code/modules/clothing/under/costume.dm
  austation/code/modules/clothing/under/miscellaneous.dm
  austation/code/modules/clothing/under/skirt_dress.dm
  austation/code/modules/vending/clothesmate.dm
  austation/icons/mob/uniform.dmi
  austation/icons/obj/clothing/uniforms.dmi
  austation/includes.dm
Labels: Feature, Sprites

#2240 Fixes loafer deleting people on it being destroyed
  austation/code/modules/recycling/disposal/loafer.dm
Labels: Fix

#2175 Felinid rework 2 electric boogaloo
  austation/code/datums/mutations/body.dm
  austation/code/datums/mutations/speech.dm
  austation/code/modules/mob/living/carbon/human/species_type/felinid.dm
  austation/code/modules/surgery/organs/eyes.dm
  austation/includes.dm
  code/modules/mob/living/living.dm
  code/modules/shuttle/on_move.dm
Labels: Balance/Rebalance, Feature, Tweak

#2189 Service borgs can now cook and miner borgs get a plasma cutter
  austation/code/game/objects/items/robot/robot_items.dm
  austation/code/game/objects/items/robot/robot_upgrades.dm
  austation/code/modules/research/designs/mechfabricator_designs.dm
  austation/includes.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#2207 Bonfires push heat
  austation/code/modules/hydroponics/grown/towercap.dm
Labels: Code Improvement, Tweak

#2264 Restores cat surgeon
  austation/code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
  austation/includes.dm
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
Labels: Tweak

#2246 Adds a generic dexterous mob for admins to use
  austation/code/modules/mob/living/simple_animal/hostile/generic.dm
  austation/includes.dm
Labels: Feature

#2271 Updates austation map
  _maps/map_files/Austation/Austation.dmm
Labels: Feature, Map Edit

#2276 Captains Hardsuit New Sprites
  austation/code/modules/clothing/spacesuit/hardsuit.dm
  austation/icons/mob/clothing/suit.dmi
  austation/icons/mob/head.dmi
  austation/icons/obj/clothing/hats.dmi
  austation/icons/obj/clothing/suit.dmi
  austation/includes.dm
Labels: Sprites

#2278 Removes borg combat spinning
  code/datums/components/riding.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Balance/Rebalance, Removal

#2281 Cloning uses less synthflesh
  code/game/machinery/cloning.dm
Labels: Tweak

#2298 Set proper required_players for heresy gamemode
  code/game/gamemodes/eldritch_cult/eldritch_cult.dm
Labels: High Priority, Tweak

#2310 fixes thanos car
  austation/code/modules/vehicles/cars/thanoscar.dm
Labels: Fix
