Repository austation/austation, pull requests merged in 2020-11, with the labels that each got.

#2456 Fix science shuttle+dock
  _maps/map_files/Austation/Austation.dmm
  _maps/shuttles/science_outpost_aus.dmm
  code/datums/shuttles.dm
Labels: Map Edit, Tweak

#2511 NO NOT THE BEES!?!?!
  austation/code/datums/diseases/advance/symptoms/beesymptom.dm
Labels: Fix

#2512 Mechs suck up ores properly, as they walk past them
  code/game/mecha/working/ripley.dm
Labels: Code Improvement

#2424 Adds The Nuclear Reactor To Cargo
  _maps/templates/reactor_1.dmm
  austation/code/modules/cargo/packs/packs.dm
  austation/code/modules/mining/equipment/survival_pod.dm
  austation/code/modules/mining/shelters.dm
  austation/code/modules/power/reactor/fuel_rods.dm
  austation/code/modules/power/reactor/rbmk.dm
  austation/code/modules/power/reactor/reactor_cargo.dm
  austation/includes.dm
Labels: Feature, Map Edit, Tweak

#2485 Refactors fuel_rods.dm a bit and adds bananium fuel rods
  austation/code/modules/cargo/packs/packs.dm
  austation/code/modules/power/reactor/fuel_rods.dm
  austation/code/modules/uplink/uplink_items.dm
  austation/icons/obj/control_rod.dmi
Labels: Feature, Terra Approved

#2401 Reactor alarms
  austation/code/modules/power/reactor/rbmk.dm
Labels: Administration, Fix, Pending Fix

#2357 Drone refresh 2
  austation/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  austation/code/modules/mob/living/simple_animal/friendly/drone/say.dm
  austation/code/modules/research/designs/mechfabricator_designs.dm
  austation/includes.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Tweak

#2546 Modularize Techweb Changes
  austation/code/modules/research/techweb/_techweb_node.dm
  austation/code/modules/research/techweb/all_nodes.dm
  austation/includes.dm
  code/controllers/subsystem/research.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Code Improvement

#2573 Face hugger surprise
  austation/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Code Improvement, Feature

#2534 Fixes a game breaking roboticist bug
  austation/code/modules/clothing/under/jobs/engineering.dm
  austation/code/modules/clothing/under/jobs/medisci.dm
  austation/code/modules/vending/wardrobes.dm
  code/game/mecha/mecha_topic.dm
Labels: Fix

#2548 Discord roundend summary
  austation/code/_HELPERS/roundend.dm
  austation/includes.dm
Labels: Feature

#2562 [PORT] Disposable sentry gun for engineer traitors
  austation/code/game/machinery/porta_turret/portable_turret.dm
  austation/code/game/objects/items/devices/traitordevices.dm
  austation/code/modules/uplink/uplink_items.dm
  austation/includes.dm
Labels: Feature, Port

#2560 Crossbow
  austation/code/datums/components/crafting/recipes.dm
  austation/code/modules/projectiles/guns/ballistic/crossbow.dm
  austation/icons/mob/inhands/items_lefthand.dmi
  austation/icons/mob/inhands/items_righthand.dmi
  austation/icons/obj/crossbow.dmi
  austation/includes.dm
Labels: Feature, Port

#2603 Makes the discord roundend actually work
  austation/code/_HELPERS/roundend.dm
Labels: Fix, High Priority

#2610 Revert "Face hugger surprise"
  austation/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Revert

#2629 Removes TG maintainers from code owners
  .github/CODEOWNERS
Labels: GitHub, Removal

#2632 [PORT] Ports tail entwining from /tg/station
  code/modules/mob/living/living.dm
Labels: Feature, Port

#2643 Fixes roundend newlines
  austation/code/_HELPERS/roundend.dm
Labels: Fix

#2631 Restart votes doesn't ignore deadmins anymore
  code/controllers/subsystem/vote.dm
Labels: Administration

#2648 Fixes roundend channelantag objectives
  austation/code/_HELPERS/roundend.dm
Labels: Fix

#2641 Fixes invisible crates on the austation map
  _maps/map_files/Austation/Austation.dmm
Labels: Fix, Map Edit

#2656 Proper roundend discordmsg emptying
  austation/code/_HELPERS/roundend.dm
Labels: Fix

#2561 Adds a reagent dart gun for crew
  austation/code/modules/projectiles/guns/misc/chem_gun.dm
  austation/code/modules/research/designs/medical_designs.dm
  austation/code/modules/research/techweb/all_nodes.dm
  austation/includes.dm
Labels: Feature
