Repository austation/austation, pull requests merged in 2020-10, with the labels that each got.

#2277 Captains Hat Tweak
  austation/code/modules/clothing/head/job.dm
  austation/includes.dm
Labels: Tweak

#2286 Adds supermatter bread
  austation/code/datums/components/crafting/recipes.dm
  austation/code/modules/food_and_drinks/food/snacks_bread.dm
  austation/code/modules/food_and_drinks/food/tablecraft/recipes_bread.dm
  austation/code/modules/recycling/disposal/loafer.dm
  austation/icons/obj/food/burgerbread.dmi
  austation/includes.dm
  code/datums/components/crafting/crafting.dm
Labels: Code Improvement, Feature

#2346 You can now lick people
  austation/code/modules/mob/mob.dm
Labels: Critical Priority, Feature

#2349 Fixes licking
  austation/code/modules/mob/mob.dm
Labels: Fix

#2351 Revert "Fixes licking"
  austation/code/modules/mob/mob.dm
Labels: Revert

#2352 Revert "You can now lick people"
  austation/code/modules/mob/mob.dm
Labels: Revert

#2311 Prevents Cut Cable From Being Magically Red
  austation/code/modules/power/cable.dm
  austation/includes.dm
Labels: Fix

#2375 [Port] Ports NSV13's rbmk fission reactor
  _maps/map_files/Austation/Austation.dmm
  austation/code/_HELPERS/matrices.dm
  austation/code/modules/power/rbmk.dm
  austation/icons/obj/computer.dmi
  austation/icons/obj/control_rod.dmi
  austation/icons/obj/inflatable.dmi
  austation/icons/obj/machinery/rbmk.dmi
  austation/icons/obj/machinery/reactor_parts.dmi
  austation/includes.dm
  austation/sound/effects/rbmk/alarm.ogg
  austation/sound/effects/rbmk/meltdown.ogg
  austation/sound/effects/rbmk/reactor_hum.ogg
  austation/sound/effects/rbmk/switch.ogg
  austation/sound/effects/rbmk/switch2.ogg
  austation/sound/effects/rbmk/switch3.ogg
  austation/sound/effects/rbmk/turbine_end.ogg
  austation/sound/effects/rbmk/turbine_mid.ogg
  austation/sound/effects/rbmk/turbine_start.ogg
  austation/sound/effects/ship/freespace2/crane_1.wav
  austation/sound/effects/ship/reactor/falloutwind.ogg
  austation/sound/effects/ship/reactor/startup.ogg
  austation/sound/effects/ship/reactor/startup2.ogg
  code/__DEFINES/sound.dm
  code/modules/modular_computers/computers/machinery/console_presets.dm
  tgui/packages/tgui/interfaces/NtosRbmkStats.js
  tgui/packages/tgui/interfaces/RbmkControlRods.js
  tgui/packages/tgui/interfaces/RbmkStats.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Map Edit, Port, UI

#2387 Rings now tied to body, not client
  austation/code/modules/mob/living/carbon/human/examine.dm
  austation/code/modules/mob/living/carbon/human/human_defines.dm
  austation/code/modules/mob/mob.dm
  austation/code/modules/mob/mob_defines.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix, Grammar and Formatting, Tweak

#2388 fixes some bugs with the reactor port
  _maps/map_files/Austation/Austation.dmm
Labels: Fix, Map Edit, Tweak

#2396 adds co2 can to reactor room
  _maps/map_files/Austation/Austation.dmm
Labels: Feature, Map Edit

#2397 Fixes reactor access
  _maps/map_files/Austation/Austation.dmm
Labels: Fix, Map Edit

#2399 Connects the reactors APC to the SMES
  _maps/map_files/Austation/Austation.dmm
Labels: Feature, Map Edit

#2402 Uranium 235 and grammer for the nuclear reactor who fucking coded this.
  austation/code/modules/power/rbmk.dm
Labels: Fix

#2403 Changelings now copy rings
  austation/code/modules/antagonists/changeling/changeling.dm
  austation/includes.dm
  code/game/gamemodes/changeling/changeling.dm
  code/modules/antagonists/changeling/changeling.dm
Labels: Tweak

#2393 Adds Telecrystal Fuel Rods
  austation/code/modules/power/fuel_rods.dm
  austation/code/modules/uplink/uplink_items.dm
  austation/icons/obj/control_rod.dmi
  austation/includes.dm
Labels: Feature

#2405 [PORT] Table Changes From Cit (Mostly)
  austation/code/game/objects/items/stacks/sheets/glass.dm
  austation/code/game/objects/structures/tables_racks.dm
  austation/code/modules/mob/living/pseudo_z_axis.dm
  austation/icons/obj/smooth_structures/plasmaglass_table.dmi
  austation/includes.dm
  austation/sound/misc/tableslap.ogg
Labels: Feature, Port, Tweak

#2395 Borg hug module now provides a mood buff
  code/game/objects/items/robot/robot_items.dm
Labels: Feature

#2392 Makes pools reduce rad emit strength
  austation/code/_HELPERS/radiation.dm
  austation/code/game/atoms.dm
  austation/includes.dm
Labels: Tweak

#2417 Updates AuStation Map
  _maps/map_files/Austation/Austation.dmm
Labels: Map Edit

#2404 Adds fuel rods to cargo console
  austation/code/modules/cargo/packs/packs.dm
Labels: Feature

#2416 Fuel rod rework, depleted fuel and includes fix and more
  austation/code/modules/cargo/exports/engineering.dm
  austation/code/modules/power/fuel_rods.dm
  austation/includes.dm
Labels: Balance/Rebalance, Code Improvement, Feature, Fix

#2355 Viro Reconfigure
  austation/code/datums/components/spikes.dm
  austation/code/datums/diseases/advance/symptoms/beesymptom.dm
  austation/code/datums/diseases/advance/symptoms/deafness.dm
  austation/code/datums/diseases/advance/symptoms/fever.dm
  austation/code/datums/diseases/advance/symptoms/fire.dm
  austation/code/datums/diseases/advance/symptoms/flesh_eating.dm
  austation/code/datums/diseases/advance/symptoms/genetics.dm
  austation/code/datums/diseases/advance/symptoms/heal.dm
  austation/code/datums/diseases/advance/symptoms/nanites.dm
  austation/code/datums/diseases/advance/symptoms/narcolepsy.dm
  austation/code/datums/diseases/advance/symptoms/oxygen.dm
  austation/code/datums/diseases/advance/symptoms/symptoms.dm
  austation/code/datums/diseases/advance/symptoms/viral.dm
  austation/code/datums/diseases/advance/symptoms/vision.dm
  austation/code/datums/diseases/advance/symptoms/vomit.dm
  austation/code/datums/diseases/advance/symptoms/weight.dm
  austation/includes.dm
  code/datums/diseases/advance/symptoms/oxygen.dm
Labels: Balance/Rebalance, Refactor, Tweak

#2398 Ports glass floors from /vg/
  austation/code/game/turfs/open/floor_glass.dm
  austation/code/game/turfs/open/space/space.dm
  austation/icons/obj/items.dmi
  austation/icons/obj/structures.dmi
  austation/icons/turf/overlays.dmi
  austation/includes.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/turfs/open/floor/plating.dm
  code/game/turfs/open/space/space.dm
Labels: Feature

#2426 [s] Adds The Opposite Of Stealth Mode; Obnoxious Mode!
  austation/code/modules/admin/admin_verbs.dm
  austation/icons/mob/mob.dmi
  austation/includes.dm
  code/modules/admin/admin_verbs.dm
Labels: Administration

#2431 Fixes TC rods
  austation/code/modules/power/fuel_rods.dm
Labels: Fix

#2356 Adds professor membrane's gloves and labcoat
  austation/code/game/objects/items.dm
  austation/code/game/objects/structures/closets/secure.dm
  austation/code/modules/clothing/gloves/color.dm
  austation/code/modules/clothing/suits/miscellaneous.dm
  austation/icons/mob/clothing/custom_w.dmi
  austation/icons/mob/inhands/weapons/darksabre_lefthand.dmi
  austation/icons/mob/inhands/weapons/darksabre_righthand.dmi
  austation/icons/obj/clothing/custom.dmi
  austation/includes.dm
Labels: Feature

#2423 Moves the toxins tesing site away from the nuclear reactor.
  _maps/map_files/Austation/Austation.dmm
Labels: Fix, Map Edit

#2436 fixes jagerbomb round bug
  austation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Fix

#2406 [Emotes] You can now say beans and cheese
  austation/code/modules/mob/living/carbon/human/emote.dm
  austation/sound/misc/beans.ogg
  austation/sound/misc/cheese.ogg
Labels: Feature, Sound

#2437 Adds layer manifolds to atmos on roundstart
  _maps/map_files/Austation/Austation.dmm
Labels: Feature, Map Edit, Terra Approved

#2444 Adds the peacekeeper skirtborg model
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
  austation/icons/mob/robot.dmi
Labels: Sprites

#2445 Fixes the glass floor getting turned into plating when atmos rips it
  austation/code/game/turfs/open/floor_glass.dm
Labels: Fix

#2449 Fixes painted floors turning black when they're damaged
  austation/code/game/objects/items/devices/floor_painter.dm
  austation/code/game/turfs/open/floor.dm
  austation/icons/turf/floors.dmi
  austation/includes.dm
  code/game/turfs/open/floor.dm
Labels: Fix

#2463 Reactor TGUI Fix
  austation/code/modules/power/rbmk.dm
Labels: Critical Priority, Fix, UI

#2435 Adds more quirks
  austation/code/datums/traits/neutral.dm
  austation/includes.dm
Labels: Feature

#2480 Adds sprites for standard and syndie assault borg, one more for peackekeeper
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
  austation/icons/mob/robot.dmi
Labels: Feature
