Repository austation/austation, pull requests merged in 2021-01, with the labels that each got.

#2850 Neurotoxin b a l a n c e
  code/modules/projectiles/projectile/special/neurotoxin.dm
Labels: Balance/Rebalance

#2851 [s] Revert "Neurotoxin b a l a n c e"
  code/modules/projectiles/projectile/special/neurotoxin.dm
Labels: Revert

#2865 Revert "Revert "[MIRROR] Adds the old gas mask back.""
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Revert, Sprites, Upstream PR Merged

#2866 new comms console param
  code/game/machinery/computer/communications.dm
Labels: Tweak

#2867 Changed blink sound to instant transmission
  sound/magic/blink.ogg
Labels: Sound

#2883 Revert "Prevents Cut Cable From Being Magically Red"
  austation/code/modules/power/cable.dm
  austation/includes.dm
Labels: Revert

#2919 Fixes the new errors in vscode relating to mapwriter
  austation/code/modules/mapping/writer.dm
Labels: Fix, Terra Approved

#2918 You can now give items to people by pressing "G"
  austation.dme
  austation/code/_onclick/hud/alert.dm
  austation/code/datums/keybinding/carbon.dm
  austation/code/modules/mob/living/carbon/inventory.dm
Labels: Feature

#2924 blank messages won't appear in discord ooc anymore
  austation/code/modules/client/verbs/ooc.dm
Labels: Fix

#2958 Ports #2908 Metastation changes to Austation.dmm
  _maps/map_files/Austation/Austation.dmm
Labels: Map Edit, Tweak
