Repository austation/austation, pull requests merged in 2021-11, with the labels that each got.

#4370 Cap Hardsuit Sprite Fix
  austation/icons/mob/clothing/suit.dmi
Labels: Fix

#4362 Modularizes Gympie sprites, properly this time, adds gympies back, & tweaks aspects.
  austation.dme
  austation/code/modules/hydroponics/grown/gympie_gympie.dm
  austation/code/modules/mob/living/simple_animal/hostile/gympie_gympie.dm
  austation/code/modules/uplink/uplink_items.dm
  austation/icons/obj/hydroponics/popes_selection.dmi
Labels: Sprites

#4359 Explosive Plant Nerf
  austation/code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  austation/code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Labels: Tweak, Balance/Rebalance

#4409 get rid of the leftover tgui files
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
Labels: UI

#4365 Removes stimulum from strange seed pool
  austation/code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Removal, Balance/Rebalance

#4383 Discovery Research Removal
  austation.dme
  austation/code/modules/research/techweb/_techweb_node.dm
  austation/code/modules/research/techweb/all_nodes.dm
  austation/code/modules/shuttle/super_cruise/orbital_poi_generator/loot/research_disks.dm
Labels: Tweak, Terra Approved

#4459 Modular ancestor voice pack
  austation.dme
  austation/code/datums/announcers/ancestor_announcer.dm
  austation/code/datums/station_traits/neutral_traits.dm
  austation/sound/ai/ancestor/aimalf.ogg
  austation/sound/ai/ancestor/aliens.ogg
  austation/sound/ai/ancestor/animes.ogg
  austation/sound/ai/ancestor/attention.ogg
  austation/sound/ai/ancestor/commandreport.ogg
  austation/sound/ai/ancestor/granomalies.ogg
  austation/sound/ai/ancestor/intercept.ogg
  austation/sound/ai/ancestor/ionstorm.ogg
  austation/sound/ai/ancestor/meteors.ogg
  austation/sound/ai/ancestor/outbreak5.ogg
  austation/sound/ai/ancestor/outbreak7.ogg
  austation/sound/ai/ancestor/poweroff.ogg
  austation/sound/ai/ancestor/poweron.ogg
  austation/sound/ai/ancestor/radiation.ogg
  austation/sound/ai/ancestor/shuttlecall.ogg
  austation/sound/ai/ancestor/shuttledock.ogg
  austation/sound/ai/ancestor/shuttlerecalled.ogg
  austation/sound/ai/ancestor/spanomalies.ogg
  austation/sound/ai/ancestor/welcome/welcome1.ogg
  austation/sound/ai/ancestor/welcome/welcome2.ogg
  code/datums/station_traits/neutral_traits.dm
Labels: Sound, Terra Approved

#4471 let people use PDAs to open firelocks
  code/game/machinery/doors/firedoor.dm
Labels: Tweak

#4475 Fix Autosandbox
  austation.dme
  austation/code/controllers/subsystem/autosandbox.dm
  austation/code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/ticker.dm
Labels: Fix

#4460 Gympie Gympie Additions
  austation/code/modules/hydroponics/grown/gympie_gympie.dm
Labels: Feature

#4487 unfucks crossed
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/stairs.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/modules/ruins/objects_and_mobs/necropolis_gate.dm
Labels: Fix
