Repository austation/austation, pull requests merged in 2021-09, with the labels that each got.

#4040 [PORT] Removes rad immunity from IPCs and gives them NSV's radiation interaction
  austation.dme
  austation/code/__DEFINES/traits.dm
  austation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  austation/code/modules/reagents/chemistry/recipes/medicine.dm
  code/datums/weather/weather_types/radiation_storm.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
Labels: Removal, Balance/Rebalance, Port

#4079 mirror supercruise meta map changes to au
  _maps/map_files/Austation/Austation.dmm
Labels: Map Edit

#4146 make jukebuild notice changes from austation modular changes
  tools/build/build.js
Labels: Tools

#4189 fixes radioactive disinfectant
  austation/code/modules/reagents/chemistry/recipes/medicine.dm
Labels: Fix

#4169 Value package PR
  austation/code/modules/coilgun/projectile.dm
  austation/code/modules/food_and_drinks/food/snacks_bread.dm
  austation/code/modules/food_and_drinks/food/tablecraft/recipes_bread.dm
  austation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  austation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  austation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  austation/code/modules/recycling/disposal/loafer.dm
  austation/code/modules/recycling/disposal/pipe.dm
  code/__HELPERS/unsorted.dm
Labels: Tweak, Balance/Rebalance, Fix, Code Improvement

#4217 REDACTED
  austation/code/game/objects/items/plushes.dm
  austation/icons/obj/plushes.dmi
  austation/sound/misc/gnue.ogg
Labels: Feature

#4219 Revert "REDACTED"
  austation/code/game/objects/items/plushes.dm
  austation/icons/obj/plushes.dmi
  austation/sound/misc/gnue.ogg
Labels: Revert, Terra Approved, Critical Priority

#4221 Remove Fumos
  austation.dme
  austation/code/game/objects/items/plushes.dm
  austation/icons/obj/plushes.dmi
Labels: Removal, RED LABEL, Terra Approved, Critical Priority

#4222 Revert "[MIRROR] Increases plasma consumption in radiation collectors…
  austation.dme
  austation/code/modules/power/singularity/collector.dm
Labels: Upstream PR Merged, Tweak, Revert

#4231 catgirls and lizards get no disease from rats
  austation.dme
  austation/code/__DEFINES/diseases.dm
  austation/code/__DEFINES/traits.dm
  austation/code/modules/mob/living/carbon/human/species_type/felinid.dm
  austation/code/modules/mob/living/carbon/human/species_type/lizardpeople.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak

#4225 extravagant suit
  austation/code/modules/clothing/suits/armor.dm
  austation/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Feature
