Repository austation/austation, pull requests merged in 2021-08, with the labels that each got.

#3919 Disboard AI law module
  austation/code/datums/ai_laws.dm
  austation/code/game/objects/items/AI_modules.dm
  austation/code/modules/research/designs/AI_module_designs.dm
  austation/code/modules/research/techweb/all_nodes.dm
Labels: Feature, Terra Approved

#3948 Reinstate bad squidnames
  austation/strings/names/squid_female.txt
  austation/strings/names/squid_male.txt
  code/_globalvars/lists/names.dm
Labels: Feature

#3979 tgui inputlist now locks your keyboard for ease of search
  tgui/packages/tgui/interfaces/ListInput.js
  tgui/public/tgui.bundle.js
Labels: Feature, UI

#3985 Fixes austation-specific tanks not working
  austation/code/game/objects/items/tanks/tank_types.dm
Labels: Fix

#3905 Expanded Malf Ai alert module modularised edition
  austation.dme
  austation/code/modules/events/communications_blackout.dm
  austation/code/modules/events/disease_outbreak.dm
  austation/code/modules/events/electrical_storm.dm
  austation/code/modules/events/space_dragon.dm
Labels: Feature

#4013 A Few Minor Mapping Changes 2.0
  _maps/map_files/Austation/Austation.dmm
Labels: Feature, Tweak, Fix, Map Edit

#4067 fixes rbmk
  austation/code/modules/power/reactor/rbmk.dm
Labels: Fix
