Repository austation/austation, pull requests merged in 2021-07, with the labels that each got.

#3683 Restore Orbitalstation to working order: Part 1
  _maps/map_files/OrbitalStation/OrbitalStation.dmm
  _maps/orbitalstation.json
  _maps/shuttles/emergency_orbital.dmm
  austation.dme
  austation/code/datums/shuttles.dm
Labels: Feature, Map Edit

#3690 Shotgun Revert
  austation.dme
  austation/code/modules/projectiles/ammunition/ballistic/shotgun.dm
  austation/code/modules/projectiles/gun.dm
  austation/code/modules/projectiles/guns/ballistic/ballistic.dm
  austation/code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: Revert, Tweak

#3685 Spriting Revert Misc : AKA mostly engineering shit
  austation.dme
  austation/code/game/objects/items/storage/backpack.dm
  austation/code/modules/clothing/head/hardhat.dm
  austation/code/modules/clothing/shoes/magboots.dm
  austation/code/modules/clothing/suits/jobs/engineering.dm
  austation/icons/mob/back.dmi
  austation/icons/mob/feet.dmi
  austation/icons/mob/head.dmi
  austation/icons/mob/inhands/equipment/backpack_lefthand.dmi
  austation/icons/mob/inhands/equipment/backpack_righthand.dmi
  austation/icons/obj/clothing/hats.dmi
  austation/icons/obj/clothing/shoes.dmi
  austation/icons/obj/storage.dmi
Labels: Revert, Sprites

#3718 New roundend sound
  sound/roundend/admin_abuse.ogg
Labels: Sound

#3684 Sprite Revert Tools & Parts : AKA Bee Spriters Still Suck
  austation.dme
  austation/code/game/machinery/cell_charger.dm
  austation/code/game/objects/items.dm
  austation/code/game/objects/items/devices/geiger_counter.dm
  austation/code/game/objects/items/devices/multitool.dm
  austation/code/game/objects/items/devices/scanners.dm
  austation/code/game/objects/items/inducer.dm
  austation/code/game/objects/items/storage/belt.dm
  austation/code/game/objects/items/tools/crowbar.dm
  austation/code/game/objects/items/tools/powertools.dm
  austation/code/game/objects/items/tools/screwdriver.dm
  austation/code/game/objects/items/tools/weldingtool.dm
  austation/code/game/objects/items/tools/wirecutters.dm
  austation/code/game/objects/items/tools/wrench.dm
  austation/code/modules/clothing/gloves/color.dm
  austation/code/modules/mining/equipment/mineral_scanner.dm
  austation/code/modules/power/cell.dm
  austation/code/modules/research/stock_parts.dm
  austation/icons/mob/clothing/belt.dmi
  austation/icons/mob/clothing/belt_overlays.dmi
  austation/icons/mob/clothing/gloves.dmi
  austation/icons/mob/inhands/equipment/belts_lefthand.dmi
  austation/icons/mob/inhands/equipment/belts_righthand.dmi
  austation/icons/mob/inhands/equipment/tools_lefthand.dmi
  austation/icons/mob/inhands/equipment/tools_righthand.dmi
  austation/icons/mob/inhands/tools_lefthand.dmi
  austation/icons/obj/clothing/belts.dmi
  austation/icons/obj/clothing/gloves.dmi
  austation/icons/obj/device.dmi
  austation/icons/obj/power.dmi
  austation/icons/obj/stock_parts.dmi
  austation/icons/obj/tools.dmi
Labels: Revert, Sprites

#3779 Fixed bread machines + misc improvements
  austation/code/modules/recycling/disposal/loafer.dm
Labels: Code Improvement, Fix

#3742 Syndicate Name Generation Reference 2
  code/__HELPERS/names.dm
Labels: Feature, Terra Approved

#3800 modularize x-ray
  austation.dme
  austation/code/datums/mutations/_combined.dm
  code/datums/mutations/_combined.dm
Labels: Modularized

#3752 Restore Orbitalstation to working order: Part 2
  _maps/map_files/OrbitalStation/OrbitalStation.dmm
Labels: Feature, Map Edit

#3802 add syndi mask to the meta shop
  austation.dme
  austation/code/modules/client/loadout/loadout_hat.dm
Labels: Feature

#3807 Fixes loafer runtime
  austation/code/modules/recycling/disposal/loafer.dm
Labels: Fix

#3812 fixes necro chest lookup table
  austation/code/modules/mining/lavaland/necropolis_chests.dm
Labels: Fix

#3813 fixes bread fixes
  austation/code/modules/food_and_drinks/food/snacks_bread.dm
  austation/code/modules/recycling/disposal/loafer.dm
Labels: Fix

#3836 fix some CRLF line endings
  TGS3.json
  config/ooc_filter.txt
  html/antagtips/abductor.html
  html/antagtips/blob.html
  html/antagtips/changeling.html
  html/antagtips/cult.html
  html/antagtips/nukie.html
  html/antagtips/traitor.html
  html/antagtips/wizard.html
  html/antagtips/xeno.html
  html/archivedchangelog.html
  html/browser/common.css
  html/browser/scannernew.css
  html/changelog.css
  html/create_object.html
Labels: Config Update, Tweak

#3839 fix icon for circuits multitool
  austation.dme
  austation/code/modules/wiremod/marker.dm
Labels: Fix

#3766 Hardsuit Sprite Revert Excluding Sec & HoS
  austation.dme
  austation/code/modules/clothing/spacesuit/hardsuit.dm
  austation/code/modules/clothing/spacesuit/syndi.dm
  austation/icons/mob/clothing/suit.dmi
  austation/icons/mob/head.dmi
  austation/icons/mob/inhands/clothing_lefthand.dmi
  austation/icons/mob/inhands/clothing_righthand.dmi
  austation/icons/obj/clothing/hats.dmi
  austation/icons/obj/clothing/suit.dmi
Labels: Revert, Tweak

#3866 Fumo
  austation.dme
  austation/code/game/objects/items/plushes.dm
  austation/icons/obj/plushes.dmi
Labels: Feature

#3848 Adds haram sound effect for clown synthesier
  austation.dme
  austation/code/game/objects/items/devices/sound_synth.dm
  austation/sound/effects/haram_alarm.ogg
Labels: Feature, Sound

#3867 Another fumo
  austation/code/game/objects/items/plushes.dm
  austation/icons/obj/plushes.dmi
Labels: Feature

#3903 Round Start Austation Airlock Fix
  _maps/map_files/Austation/Austation.dmm
Labels: Fix, Map Edit

#3910 Store tickets in database
  SQL/austation_schema.sql
  SQL/database_changelog.txt
  austation.dme
  austation/code/controllers/subsystem/blackbox.dm
  code/__DEFINES/subsystems.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Administration, SQL, Terra Approved
