Repository austation/austation, pull requests merged in 2021-12, with the labels that each got.

#4515 fix autosandbox not counting all players
  austation/code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/ticker.dm
Labels: Fix

#4560 Malf Borg Stun Baton No Puss Puss *ceritfied balance*
  austation/code/game/objects/items/robot/robot_items.dm
Labels: Balance/Rebalance

#4498 removes piping from viro and ai sat
  _maps/map_files/Austation/Austation.dmm
Labels: Removal, Tweak, Map Edit

#4379 Tcomm filtering
  austation.dme
  austation/code/game/machinery/telecomms/machines/server.dm
  code/game/machinery/telecomms/computers/logbrowser.dm
  code/game/machinery/telecomms/machines/server.dm
Labels: Feature, Currently Testmerged

#4521 ports the toilet bong from yogstation
  austation.dme
  austation/code/__DEFINES/dcs/signals.dm
  austation/code/datums/components/storage/storage.dm
  austation/code/game/objects/structures/toilet_bong.dm
  austation/code/game/objects/structures/watercloset.dm
  austation/icons/obj/watercloset.dmi
Labels: Feature, Terra Approved

#4535 Mechfabs no longer crash after building a drone shell
  austation/code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  austation/code/modules/research/designs/mechfabricator_designs.dm
Labels: Feature, Tweak

#4608 Makes the Ancestor announcer slightly more common
  austation/code/datums/station_traits/neutral_traits.dm
Labels: Tweak

#4610 incomprehensibly buffs AI
  code/_globalvars/lists/flavor_misc.dm
  icons/mob/ai.dmi
Labels: Sprites, Terra Approved

#4616 Revert "Tcomm filtering (#4379)"
  austation.dme
  austation/code/game/machinery/telecomms/machines/server.dm
  code/game/machinery/telecomms/computers/logbrowser.dm
  code/game/machinery/telecomms/machines/server.dm
Labels: Removal, Revert
