Repository austation/austation, pull requests merged in 2021-02, with the labels that each got.

#2999 Removes the old pool
  _maps/RandomRooms/10x10/sk_rdm210_pool.dmm
  _maps/map_files/Austation/Austation.dmm
  austation.dme
  austation/code/_DEFINES/pool.dm
  austation/code/_DEFINES/traits.dm
  austation/code/_HELPERS/radiation.dm
  austation/code/_globalvars/pool_globals.dm
  austation/code/datums/elements/swimming.dm
  austation/code/game/atoms.dm
  austation/code/game/sound.dm
  austation/code/modules/mapping/random_rooms.dm
  austation/code/modules/pool/pool_controller.dm
  austation/code/modules/pool/pool_drain.dm
  austation/code/modules/pool/pool_effects.dm
  austation/code/modules/pool/pool_main.dm
  austation/code/modules/pool/pool_noodles.dm
  austation/code/modules/pool/pool_structures.dm
  austation/code/modules/pool/pool_wires.dm
  austation/icons/turf/pool.dmi
  austation/sound/effects/fillingwatter.ogg
  austation/sound/effects/pooldrain.ogg
  austation/sound/effects/slosh.ogg
  austation/sound/effects/slosh1.ogg
  austation/sound/effects/slosh2.ogg
  austation/sound/effects/splash.ogg
  austation/sound/effects/water_wade1.ogg
  austation/sound/effects/water_wade2.ogg
  austation/sound/effects/water_wade3.ogg
  austation/sound/effects/water_wade4.ogg
  austation/sound/effects/watersplash.ogg
Labels: Map Edit, Removal

#3005 Adds in the new pool
  _maps/RandomRooms/10x10/sk_rdm210_pool.dmm
  _maps/map_files/Austation/Austation.dmm
  austation/code/modules/mapping/random_rooms.dm
Labels: Feature, Map Edit

#3017 Adds in the missing reactor rod pool
  _maps/map_files/Austation/Austation.dmm
Labels: Critical Priority, Fix, Map Edit

#2959 Admins can now kill radiations
  austation.dme
  austation/code/modules/admin/verbs/kill_rads.dm
  code/modules/admin/admin_verbs.dm
Labels: Administration

#3061 removes white dots
  austation/icons/mob/clothing/custom_w.dmi
Labels: Fix

#3062 bees now die when stinging a living target
  austation.dme
  austation/code/modules/mob/living/simple_animal/hostile/bees.dm
Labels: Balance/Rebalance

#2974 New roundend sound
  sound/roundend/christian_roundend.ogg
Labels: Sound

#2901 Increases viability of minebots
  austation.dme
  austation/code/modules/mining/machine_vending.dm
  austation/code/modules/mining/minebot.dm
  austation/code/modules/research/techweb/all_nodes.dm
  code/modules/mining/machine_vending.dm
Labels: Balance/Rebalance, Feature, Removal, Tweak

#3112 fixes __DEFINES and __HELPERS
  austation.dme
  austation/code/__DEFINES/admin.dm
  austation/code/__DEFINES/misc.dm
  austation/code/__DEFINES/mobs.dm
  austation/code/__DEFINES/movespeed_modification.dm
  austation/code/__DEFINES/traits.dm
  austation/code/__HELPERS/matrices.dm
  austation/code/__HELPERS/roundend.dm
Labels: Code Improvement, Fix

#3123 adds missing return to plating.dm
  code/game/turfs/open/floor/plating.dm
Labels: Fix

#3045 Overdose and Addiction Are Triggered When Reagents Are ABOVE Threshold
  code/modules/reagents/chemistry/holder.dm
Labels: Tweak

#3088 gives service borgs back their tray
  austation/code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Feature
