Repository austation/austation, pull requests merged in 2021-03, with the labels that each got.

#3089 CTRL+click jumpsuits to cycle sensors.
  austation.dme
  austation/code/modules/clothing/clothing.dm
Labels: Feature

#3171 Weapon rechargers display that they have finished charging on the same cycle they finish
  code/game/machinery/recharger.dm
Labels: Fix

#3133 Species with tails now wag their tails when headpatted
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Feature

#3165 Adds the cake printer 2.0: Return of the katcode
  austation.dme
  austation/code/game/objects/items/circuitboards/machine_circuitboards.dm
  austation/code/modules/food_and_drinks/food/kitchen_machinery/cake_printer.dm
  austation/code/modules/food_and_drinks/food/snacks_bread.dm
  austation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  austation/code/modules/reagents/chemistry/recipes/others.dm
  austation/code/modules/research/designs/machine_designs.dm
  austation/code/modules/research/techweb/all_nodes.dm
  austation/icons/obj/machines/cake_printer.dmi
Labels: Feature

#3253 Adds content with the surgery content PR #3216 to austation
  _maps/map_files/Austation/Austation.dmm
Labels: Map Edit

#3238 Improves crew moral via whipping
  austation.dme
  austation/code/datums/mood_event/generic_positive_events.dm
  austation/code/game/objects/items/melee/misc.dm
Labels: Feature, Terra Approved

#3287 Nerfs Lostman
  austation/icons/obj/clothing/hats_deconflict.dmi
  austation/icons/obj/clothing/uniforms_deconflict.dmi
Labels: Removal
