Repository austation/austation, pull requests merged in 2021-10, with the labels that each got.

#4258 Gasoline
  austation.dme
  austation/code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  austation/code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  austation/code/modules/reagents/reagent_containers/glass.dm
  austation/icons/obj/chemical.dmi
  code/_globalvars/lists/maintenance_loot.dm
Labels: Feature

#4273 idk apparently recipe for gasoline/petrol can't be done
  austation/code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  austation/code/modules/reagents/reagent_containers/glass.dm
Labels: Fix

#4285 rats leave mouse corpses instead of being deleted.
  austation/code/modules/mob/living/simple_animal/hostile/regalrat.dm
Labels: Tweak
