Repository austation/austation, pull requests merged in 2021-06, with the labels that each got.

#2541 The Disposal Coilgun! Or how I learnt to stop rod spamming and love magnets
  .github/CODEOWNERS
  _maps/templates/au_coilgun_small.dmm
  austation.dme
  austation/code/__DEFINES/RPD.dm
  austation/code/__DEFINES/coilgun.dm
  austation/code/__DEFINES/maths.dm
  austation/code/_globalvars/coilgun.dm
  austation/code/game/atoms.dm
  austation/code/game/machinery/pipe/pipe_dispenser.dm
  austation/code/game/objects/items/RPD.dm
  austation/code/game/objects/structures/window.dm
  austation/code/game/turf.dm
  austation/code/game/turfs/closed/_closed.dm
  austation/code/game/turfs/closed/walls.dm
  austation/code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  austation/code/modules/coilgun/_coilgun.dm
  austation/code/modules/coilgun/barrel/barrel.dm
  austation/code/modules/coilgun/barrel/barrel_builder.dm
  austation/code/modules/coilgun/charger.dm
  austation/code/modules/coilgun/modifier.dm
  austation/code/modules/coilgun/projectile.dm
  austation/code/modules/coilgun/segments.dm
  austation/code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
  austation/code/modules/power/singularity.dm
  austation/code/modules/projectiles/projectile.dm
  austation/code/modules/recycling/disposal/construction.dm
  austation/code/modules/recycling/disposal/holder.dm
  austation/code/modules/recycling/disposal/loafer.dm
  austation/code/modules/recycling/disposal/pipe.dm
  austation/icons/obj/atmospherics/pipes/disposal.dmi
  austation/icons/obj/power.dmi
  austation/strings/coilgun/bluespace.txt
  austation/strings/coilgun/bouncy.txt
  austation/strings/coilgun/sticky.txt
  austation/strings/coilgun/void.txt
  code/game/objects/items/RPD.dm
  code/modules/projectiles/projectile.dm
Labels: Feature, GitHub, Map Edit, Needs Review, RED LABEL

#3663 Revert Modular Jumpskirts
  austation.dme
  austation/code/modules/client/preferences_savefile.dm
  austation/code/modules/clothing/under/color.dm
  austation/code/modules/clothing/under/jobs/civilian/civilian.dm
  austation/code/modules/clothing/under/jobs/engineering.dm
  austation/code/modules/clothing/under/jobs/medisci.dm
  austation/code/modules/clothing/under/jobs/security.dm
  austation/code/modules/clothing/under/miscellaneous.dm
  austation/code/modules/jobs/job_types/assistant.dm
  austation/code/modules/mob/living/carbon/human/human_defines.dm
  austation/code/modules/vending/autodrobe.dm
  austation/code/modules/vending/clothesmate.dm
  austation/code/modules/vending/wardrobes.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
Labels: Removal, Revert

#3664 Fixes a few issues with the cargo RBMK / AGCNR
  austation/code/modules/power/reactor/reactor_cargo.dm
Labels: Fix

#3688 Syndicate Name Generation Brigador Reference
  code/__HELPERS/names.dm
Labels: Feature

#3693 Refactors AU Viro To Be Inline With Bee
  austation/code/datums/diseases/advance/symptoms/beesymptom.dm
  austation/code/datums/diseases/advance/symptoms/deafness.dm
  austation/code/datums/diseases/advance/symptoms/fever.dm
  austation/code/datums/diseases/advance/symptoms/fire.dm
  austation/code/datums/diseases/advance/symptoms/flesh_eating.dm
  austation/code/datums/diseases/advance/symptoms/genetics.dm
  austation/code/datums/diseases/advance/symptoms/heal.dm
  austation/code/datums/diseases/advance/symptoms/narcolepsy.dm
  austation/code/datums/diseases/advance/symptoms/vision.dm
  austation/code/datums/diseases/advance/symptoms/vomit.dm
  austation/code/datums/diseases/advance/symptoms/weight.dm
  code/datums/diseases/advance/symptoms/beesymptom.dm
Labels: Refactor

#3694 fix polls with playtime requirements
  code/modules/mob/dead/new_player/poll.dm
Labels: Fix
