Repository austation/austation, pull requests merged in 2022-03, with the labels that each got.

#4779 'Fix' xenobiology mapping inconsistency
  _maps/map_files/Austation/Austation.dmm
Labels: Tweak, Map Edit

#4514 Surrender Verb and Emote Overhaul (fixed)
  austation.dme
  austation/code/__DEFINES/status_effects.dm
  austation/code/_onclick/hud/alert.dm
  austation/code/datums/status_effects/debuffs.dm
  austation/code/modules/mob/living/carbon/carbon.dm
  austation/code/modules/mob/living/carbon/human/human.dm
  austation/code/modules/mob/living/carbon/human/human_defines.dm
  austation/icons/mob/actions/actions.dmi
  code/game/objects/items/handcuffs.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living.dm
Labels: Pending, Feature, Tweak

#4835 Fix Floral Spines
  austation/code/modules/hydroponics/grown.dm
  austation/code/modules/hydroponics/plant_genes.dm
  code/modules/hydroponics/grown/misc.dm
Labels: Tweak, Fix

#4449 [READY] Materialization Shiritori
  austation.dme
  austation/code/__HELPERS/type_processing.dm
  austation/code/game/materialization.dm
  austation/icons/obj/items.dmi
  austation/icons/obj/structures/magic_table.dmi
Labels: Feature, Sprites, Config Update, UI
